name: Collect

on:
    # schedule:
    #   - cron:  '0 2,3,4,5,7,8,9,10 * * 1-5' #UTC
    workflow_dispatch:
    
jobs:
  deploy:
    runs-on: macos-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v1

      - name: Restore questions.json and talks.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SSO_GITHUB_TOKEN: ${{ secrets.SSO_GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: ./Scripts/restore.sh

      - name: Check questions.json
        id: check
        run: ./Scripts/check.sh questions.json

      - name: Setup
        run: brew install libressl
        if: steps.check.outputs.valid == 'true'

      - name: Cache .build
        uses: actions/cache@v2
        with:	
          path: .build
          key: ${{ runner.os }}-build-v1-${{ hashFiles('Package.swift') }}-${{ hashFiles('Package.resolved') }}
        if: steps.check.outputs.valid == 'true'

      - name: Collect
        run: swift build && .build/debug/Coala collect $SLACK_TOKEN $CHANNEL_ID
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
        if: steps.check.outputs.valid == 'true'

      - name: Cache questions.json and talks.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_RUN_ID: ${{ github.run_id }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: ./Scripts/cache.sh
        if: steps.check.outputs.valid == 'true'
        